- /blue/avery/llambre1.brown/aleph/data/aleph-data/ntuples_jetlevel/mc/output_qbb_*_train.root
- /blue/avery/llambre1.brown/aleph/data/aleph-data/ntuples_jetlevel_upsampled/output_qbb_*_train_batch*.root
