# signal samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-v2/ntuples_*_0L/mc/pieces/HHto4b_mH_125_powheg_pythia8_Run3_*_v2_1_tree.root

# QCD samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg/ntuples_*_QCD/QCD-4Jets_HT-400to600_*_tree_testing_1.root
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg/ntuples_*_QCD/QCD-4Jets_HT-600to800_*_tree_testing_1.root
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg/ntuples_*_QCD/QCD-4Jets_HT-800to1000_*_tree_testing_1.root
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg/ntuples_*_QCD/QCD-4Jets_HT-1000to1200_*_tree_testing_1.root
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg/ntuples_*_QCD/QCD-4Jets_HT-1200to1500_*_tree_testing_1.root
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg/ntuples_*_QCD/QCD-4Jets_HT-1500to2000_*_tree_testing_1.root
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg/ntuples_*_QCD/QCD-4Jets_HT-2000_*_tree_testing_1.root

# tt samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg/ntuples_*_TT/TTto*_tree_testing_1.root
