# signal samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-from-lxplus-backup/ntuples-v2-part[1,2]-feynnetpairing/ntuples_*_0L/mc/pieces/HHto4b_mH_125_*.root
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-from-lxplus-backup/ntuples-v2-part[1,2]-feynnetpairing/ntuples_*_0L/mc/pieces/HHto4b_mH_??0_*.root

# background samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-from-lxplus-backup/ntuples-data-feynnetpairing/ntuples_*_0L/data/*.root
