# signal samples
- /blue/avery/llambre1.brown/hhto4b-fit/samples-selection/output_test/*-sig/HHto4b_mH_125.root

# background samples
- /blue/avery/llambre1.brown/hhto4b-fit/samples-selection/output_test/*-data/data*.root
