# signal samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-v2/ntuples_*_0L/mc/pieces/HHto4b_mH_125_powheg_pythia8_Run3_*_v2_1_tree.root

# QCD samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg-v2/ntuples_*/QCD-4Jets_HT-400to600*_tree_*.root
