# signal samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-v2/ntuples_*_0L/mc/pieces/HHto4b_mH_125_powheg_pythia8_Run3_*_v2_0_tree.root

# QCD samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg-v2/ntuples_*/QCD*_tree_0.root

# tt samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg-v2/ntuples_*/TTto*_tree_0.root
