#####################################
# Data configuration for hh4b study #
#####################################


treename: Events

selection:
    # Define the selection for the training set
    ( (n_ak4>=3)
    & (n_ak4_btags_M>=2)
    & (alljets_ht>300)
    & (passmetfilters == 1)
    & (passjetvetomap == 1)
    & (avgbdisc_twoldgbdiscjets > 0.68)
    & (hh_average_mass > 50.) )

test_time_selection:
    # Define the selection for the testing set
    ( (n_ak4>=3)
    & (n_ak4_btags_M>=2)
    & (alljets_ht>300)
    & (passmetfilters == 1)
    & (passjetvetomap == 1)
    & (avgbdisc_twoldgbdiscjets > 0.68)
    & (hh_average_mass > 50.) )

file_magic:
  # Match file names to custom sample index
  sample:
    HHto4b_mH_125_powheg_pythia8_Run3_.+\.root: 125
    QCD.+\.root: 1

new_variables:
    # Define new variables as a function of existing variables
    hh_average_mass: (0.5*(dHH_H1_mass+dHH_H2_mass))
    isHHto4b_mH_125: sample==125
    isQCD: sample==1
    isSignal: sample==125
    isBackground: sample==1

preprocess:
   method: manual
   data_fraction: 1

inputs:
   # Define input features to the network

   input_features:
      length: 1
      vars:
         - dHH_H1_mass
         - dHH_H2_mass
         - dHH_H1_H2_deltaEta
         - dHH_H1_H2_deltaPhi
         - dHH_H1_H2_deltaR
         - dHH_H1b1_H1b2_deltaEta
         - dHH_H1b1_H1b2_deltaPhi
         - dHH_H1b1_H1b2_deltaR
         - dHH_H2b1_H1b2_deltaEta
         - dHH_H2b1_H2b2_deltaPhi
         - dHH_H2b1_H2b2_deltaR
         - dHH_H1_pt
         - dHH_H2_pt
         - dHH_HH_mass
         - dHH_HH_pt

labels:
   type: simple
   value: [isSignal, isBackground]

observers:
  # Make sure the decorrelated variable is used as observer,
  # to make post-training conclusions.
  - dHH_H1_mass
  - dHH_H2_mass
  - hh_average_mass
  - isHHto4b_mH_125
  - isQCD

weights:
   ### [option 2] compute weights on-the-fly using reweighting histograms
   use_precomputed_weights: false
   reweight_basewgt: np.ones(len(genWeight))
   reweight_method: flat
   reweight_threshold: 0
   reweight_load_fraction: 1.
   reweight_vars:
      hh_average_mass: [50., 75., 100., 125., 150., 175., 200., 225., 250., 30000.]
      alljets_ht: [0., 30000.]
   reweight_classes: [isSignal, isQCD]
   class_weights: [1, 1]
