# signal samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-v2-part2/ntuples_*_0L/mc/pieces/HHto4b_mH_125_powheg_pythia8_Run3_*_v2_*

# QCD samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-bkg-v2/ntuples_*/QCD_*_tree_1.root
