# signal samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-from-lxplus-backup/ntuples-v2-part1-feynnetpairing/ntuples_2021_0L/mc/pieces/HHto4b_mH_125_powheg_pythia8_Run3_2022-preEE_v2_0_tree.root

# background samples
- /blue/avery/llambre1.brown/hhto4b-samples/ntuples-from-lxplus-backup/ntuples-syndata-feynnetpairing/ntuples_2021_0L/data/pieces/SyntheticData_0_tree.root
